id: I444F7BCB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:41:01+00:00'
last_modified: '2022-06-07T13:39:27.266736+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20643
  title: ཕྱུགས་ནད་འགོག་བཅོས་ཤེས་བྱ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5255':
      image_group_id: I8LS20645
      title: ''
      total_pages: 129
      order: 1
      base_file: 5255.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
